version: '3'
services:
  web:
    image: nginx
    ports:
      - 8088:8888
    volumes:
      - ./src/kis.sitetheme/kis/sitetheme/resources/dist:/var/www/htdocs
      - ./buildout.d/nginx.conf:/etc/nginx/nginx.conf:ro
